In [10]:
import pandas as pd
df = pd.read_excel('final.xlsx')

In [11]:
df.head(5)

,Timestamp,PV1_Current_A,PV2_Current_A,PV1_Voltage_V,PV2_Voltage_V,PV1_Power_W,PV2_Power_W,PV_Total_Power_W,Solar_Radiation_Wm2,Outdoor_Temp_C,...,PM10_ugm3,PM1_ugm3,Indoor_Temp_C,Indoor_Humidity_pct,Indoor_Pressure_Pa,PV_imputed,hour,month,day_of_year,is_daylight
0,2026-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.192,...,18.850,8.167,8.758,75.500,101487.617,0,0,1,1.0,0
1,2026-01-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.008,...,14.950,6.550,8.487,76.700,101502.483,0,1,1,1.0,0
2,2026-01-01 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.875,...,15.017,6.417,8.333,78.700,101543.200,0,2,1,1.0,0
3,2026-01-01 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.367,...,17.317,7.567,7.933,81.017,101552.650,0,3,1,1.0,0
4,2026-01-01 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.925,...,17.033,8.033,7.430,82.733,101541.567,0,4,1,1.0,0

In [12]:
df.columns

Index(['Timestamp', 'PV1_Current_A', 'PV2_Current_A', 'PV1_Voltage_V',
       'PV2_Voltage_V', 'PV1_Power_W', 'PV2_Power_W', 'PV_Total_Power_W',
       'Solar_Radiation_Wm2', 'Outdoor_Temp_C', 'Dew_Point_C', 'Wind_Speed_ms',
       'Wind_Dir_deg', 'Pressure_hPa', 'Humidity_pct', 'UV_Index',
       'Wind_Gust_ms', 'Rain_mm', 'AQI_US', 'PM25_ugm3', 'PM10_ugm3',
       'PM1_ugm3', 'Indoor_Temp_C', 'Indoor_Humidity_pct',
       'Indoor_Pressure_Pa', 'PV_imputed', 'hour', 'month', 'day_of_year',
       'is_daylight'],
      dtype='str')

In [13]:
df.rename(columns={'PV_Total_Power_W': 'DC'}, inplace=True)

In [14]:
df.to_csv('data/final_data.csv', index=False)

In [15]:
df2=pd.read_excel('data/raw_data.xlsx')

In [16]:
df2.head()

,Timestamp,PV1_Current_A,PV2_Current_A,PV1_Voltage_V,PV2_Voltage_V,PV1_Power_W,PV2_Power_W,PV_Total_Power_W,Solar_Radiation_Wm2,Outdoor_Temp_C,...,Wind_Gust_ms,Rain_mm,AQI_US,PM25_ugm3,PM10_ugm3,PM1_ugm3,Indoor_Temp_C,Indoor_Humidity_pct,Indoor_Pressure_Pa,PV_imputed
0,2026-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.192,...,1.5,0.0,52.550,10.500,18.850,8.167,8.758,75.500,101487.617,0
1,2026-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.008,...,1.0,0.0,46.517,8.433,14.950,6.550,8.487,76.700,101502.483,0
2,2026-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.875,...,1.0,0.0,46.383,8.433,15.017,6.417,8.333,78.700,101543.200,0
3,2026-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.367,...,1.0,0.0,51.800,9.617,17.317,7.567,7.933,81.017,101552.650,0
4,2026-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8.925,...,1.5,0.0,52.767,9.983,17.033,8.033,7.430,82.733,101541.567,0

In [17]:
df2.columns

Index(['Timestamp', 'PV1_Current_A', 'PV2_Current_A', 'PV1_Voltage_V',
       'PV2_Voltage_V', 'PV1_Power_W', 'PV2_Power_W', 'PV_Total_Power_W',
       'Solar_Radiation_Wm2', 'Outdoor_Temp_C', 'Dew_Point_C', 'Wind_Speed_ms',
       'Wind_Dir_deg', 'Pressure_hPa', 'Humidity_pct', 'UV_Index',
       'Wind_Gust_ms', 'Rain_mm', 'AQI_US', 'PM25_ugm3', 'PM10_ugm3',
       'PM1_ugm3', 'Indoor_Temp_C', 'Indoor_Humidity_pct',
       'Indoor_Pressure_Pa', 'PV_imputed'],
      dtype='str')

In [18]:
df2.to_csv('data/raw_data.csv', index=False)